### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by laiyunfan** [lexibank/lairgyalrong#25]
@LinguList 
Here are the final things that we should do.
- [x] Remove unnecessary/irrelevant files.
- [x] Change language names (I have done it in etc/languages.tsv, but I wonder there is more work to do)
- [x] Update the Readme with more information, such as which file contains the dataset, Edictor link, and other necessary information

Thanks!

**Comment by LinguList** [comment]
Do you want me to remove concepts marked as "remove" in the concept list?

**Comment by LinguList** [comment]
@laiyunfan ? This is crucial for finalizing.

**Comment by laiyunfan** [comment]
Yes, those marked as "remove" should actually be removed. Thanks!

**Comment by LinguList** [comment]
@laiyunfan, you MUST modify the sources in the file `raw/sources.bib`, as they are mostly incomplete.

**Comment by LinguList** [comment]
I added the concept list to concepticon now. I also  check the representation via edictor. But the sources should be complete and nice.

**Comment by LinguList** [comment]
If you change the language names, please do not change the column LookupName, since this is what we have in our current EDICTOR.

**Comment by laiyunfan** [comment]
Sure, I will get the sources and the language names done today.

Johann-Mattis List ***@***.***>于2023年9月23日 周六12:06写道：

**Comment by LinguList** [comment]
Okay, super!

**Comment by LinguList** [comment]
Only edit the sources in `raw`. The rest is done automatically then!

**Comment by laiyunfan** [comment]
Sure!

Johann-Mattis List ***@***.***>于2023年9月23日 周六12:11写道：

**Comment by laiyunfan** [comment]
I updated the sources and checked for errors/typos there.

**Comment by LinguList** [comment]
@laiyunfan I think I have accounted for all now. Please reference Release version 0.2 in the paper. 

https://github.com/lexibank/lairgyalrong/releases/tag/v0.2

The DOI that you must mention for Zenodo archiving is [10.5281/zenodo.8383011](https://doi.org/10.5281/zenodo.8383011).

**Comment by laiyunfan** [comment]
Ok, I will update this information. Resubmission of the report scheduled this weekend.
