### ISSUE TITLE
Three languages added. 

### ISSUE THREAD

**Issue by laiyunfan** [lexibank/lairgyalrong#26]
I have added three new languages to the database: mBrongrdzong Khroskyabs, Cogtse Situ and Njorogs Khroskyabs. 
CogtseSitu.csv should replace MaerkangrGyalrong.tsv, that is to say, we won't be using MaerkangrGyalrong.tsv anymore. 

@LinguList Could you take a look and see if everything is fine, or is there anything to change?
If everything is in order, could you please integrate them into the database. 
Then I will review cognate identification again. 

There is no absolute hurry. 

Thank you very much!

Best

**Comment by LinguList** [comment]
Hi @laiyunfan, I will try to look into this in this week, but cannot promise, unfortunately.

**Comment by laiyunfan** [comment]
Thank you Mattis, there is no hurry. I would like to review the cognate judgement after adding these data, and do a Bayesian analysis and submit it somewhere.
